# Generated by Django 3.1.5 on 2021-01-27 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoSanguineo',
            fields=[
                ('id_tipos_sanguineo', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_sanguineo', models.CharField(choices=[('aPositivo', 'A+'), ('aNegativo', 'A-'), ('bPositivo', 'B+'), ('bNegativo', 'B-'), ('abPositivo', 'AB+'), ('abNegativo', 'AB-'), ('oPositivo', 'O+'), ('oNegativo', 'O-')], max_length=10, verbose_name='Tipo Sanguíneo')),
                ('doador', models.BooleanField(default=False, verbose_name='Doador')),
                ('historico_doacoes', models.TextField(verbose_name='Histórico de Doações')),
            ],
        ),
    ]
