# Generated by Django 3.1.5 on 2021-02-04 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CadastroDePessoa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoSanguineo',
            fields=[
                ('id_tipos_sanguineo', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_sanguineo', models.CharField(choices=[('aPositivo', 'A+'), ('aNegativo', 'A-'), ('bPositivo', 'B+'), ('bNegativo', 'B-'), ('abPositivo', 'AB+'), ('abNegativo', 'AB-'), ('oPositivo', 'O+'), ('oNegativo', 'O-')], max_length=10, verbose_name='Tipo Sanguíneo')),
                ('doador', models.BooleanField(default=False, verbose_name='Doador')),
                ('historico_doacoes', models.TextField(blank=True, verbose_name='Histórico de Doações')),
                ('fk_usuario_tipo_sanguineo', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='CadastroDePessoa.usuario')),
            ],
        ),
    ]
