# Generated by Django 3.1.5 on 2021-02-17 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sangue', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tiposanguineo',
            name='historico_doacoes',
        ),
    ]
