# Generated by Django 3.1.5 on 2021-02-17 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CadastroDePessoa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cirurgias',
            fields=[
                ('id_cirugias', models.AutoField(primary_key=True, serialize=False)),
                ('cirurgia', models.TextField(verbose_name='Cirurgia')),
                ('hospital', models.CharField(blank=True, max_length=200, verbose_name='Hospital')),
                ('data_cirurgia', models.DateField(verbose_name='Data da Cirurgia')),
                ('infos_extras', models.TextField(blank=True, verbose_name='Informações Extras')),
                ('fk_usuario_cirurgias', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='CadastroDePessoa.usuario')),
            ],
            options={
                'ordering': ('-data_cirurgia',),
            },
        ),
    ]
