# Generated by Django 3.1.5 on 2021-01-27 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cirurgias',
            fields=[
                ('id_cirugias', models.AutoField(primary_key=True, serialize=False)),
                ('cirurgia', models.TextField(verbose_name='Cirurgia')),
                ('motivo', models.TextField(blank=True, verbose_name='Motivo')),
                ('hospital', models.CharField(blank=True, max_length=200, verbose_name='Hospital')),
                ('data_cirurgia', models.DateField(verbose_name='Data da Cirurgia')),
                ('infos_extras', models.TextField(blank=True, verbose_name='Informações Extras')),
            ],
        ),
    ]
