# Generated by Django 3.1.5 on 2021-02-03 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cirurgias', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cirurgias',
            name='motivo',
        ),
    ]
