# Generated by Django 3.1.5 on 2021-02-04 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CadastroDePessoa', '0011_remove_usuario_cirurgias'),
        ('Cirurgias', '0002_remove_cirurgias_motivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cirurgias',
            name='fk_usuario_cirurgias',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='CadastroDePessoa.usuario'),
        ),
    ]
