# Generated by Django 3.1.5 on 2021-02-05 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Historico', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicoconsultas',
            name='atestado',
            field=models.FileField(blank=True, upload_to='atestados', verbose_name='Atestado'),
        ),
        migrations.AlterField(
            model_name='historicoconsultas',
            name='receita',
            field=models.FileField(blank=True, upload_to='receitas', verbose_name='Receita'),
        ),
    ]
