# Generated by Django 3.1.5 on 2021-02-13 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CadastroDePessoa', '0004_auto_20210212_1554'),
        ('Historico', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicofamiliar',
            name='tipo_doenca',
        ),
        migrations.AddField(
            model_name='historicofamiliar',
            name='fk_usuario_historico_familiar',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='CadastroDePessoa.usuario'),
        ),
        migrations.AlterField(
            model_name='historicoconsultas',
            name='atestado',
            field=models.FileField(blank=True, upload_to='atestados', verbose_name='Atestado'),
        ),
        migrations.AlterField(
            model_name='historicoconsultas',
            name='receita',
            field=models.FileField(blank=True, upload_to='receitas', verbose_name='Receita'),
        ),
    ]
