# Generated by Django 3.1.5 on 2021-02-03 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Historico', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicoconsultas',
            name='atestado',
            field=models.FileField(blank=True, upload_to='', verbose_name='Atestado'),
        ),
        migrations.AddField(
            model_name='historicoconsultas',
            name='receita',
            field=models.FileField(blank=True, upload_to='', verbose_name='Receita'),
        ),
    ]
