# Generated by Django 3.1.5 on 2021-02-17 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CadastroDePessoa', '0002_auto_20210216_2118'),
        ('Historico', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicoconsultas',
            options={'ordering': ('-data',)},
        ),
        migrations.RemoveField(
            model_name='historicofamiliar',
            name='tipo_doenca',
        ),
        migrations.AddField(
            model_name='historicofamiliar',
            name='fk_usuario_historico_familiar',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='CadastroDePessoa.usuario'),
        ),
        migrations.AlterField(
            model_name='historicoconsultas',
            name='atestado',
            field=models.FileField(blank=True, upload_to='atestados', verbose_name='Atestado'),
        ),
        migrations.AlterField(
            model_name='historicoconsultas',
            name='receita',
            field=models.FileField(blank=True, upload_to='receitas', verbose_name='Receita'),
        ),
        migrations.AlterField(
            model_name='historicofamiliar',
            name='doenca_hereditarias',
            field=models.TextField(verbose_name='Doenças Hereditarias'),
        ),
        migrations.CreateModel(
            name='DoencaCronica',
            fields=[
                ('id_doenca_cronica', models.AutoField(primary_key=True, serialize=False)),
                ('doenca_cronica', models.BooleanField(default=False, verbose_name='Doença Crônica')),
                ('fk_usuario_doenca_cronica', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='CadastroDePessoa.usuario')),
            ],
        ),
    ]
