# Generated by Django 3.1.5 on 2021-02-03 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Historico', '0002_auto_20210202_2239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicoconsultas',
            name='infos_extras',
        ),
    ]
