# Generated by Django 3.1.5 on 2021-02-13 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Historico', '0002_auto_20210212_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicofamiliar',
            name='doenca_cronica',
            field=models.BooleanField(default=False, verbose_name='Doença Crônica'),
        ),
    ]
