# Generated by Django 3.1.5 on 2021-02-08 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CadastroDePessoa', '0001_initial'),
        ('Historico', '0002_auto_20210205_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicofamiliar',
            name='tipo_doenca',
        ),
        migrations.AddField(
            model_name='historicofamiliar',
            name='fk_usuario_historico_familiar',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='CadastroDePessoa.usuario'),
        ),
    ]
