# Generated by Django 3.1.5 on 2021-02-13 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Historico', '0003_historicofamiliar_doenca_cronica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicofamiliar',
            name='doenca_cronica',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Não', max_length=3, verbose_name='Doença Crônica'),
        ),
    ]
