# Generated by Django 3.1.5 on 2021-02-03 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CadastroDePessoa', '0010_auto_20210203_2050'),
        ('Historico', '0003_remove_historicoconsultas_infos_extras'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicoconsultas',
            name='fk_usuario_historico_consulta',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='CadastroDePessoa.usuario'),
        ),
    ]
