# Generated by Django 3.1.5 on 2021-02-08 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Historico', '0003_auto_20210208_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicofamiliar',
            name='doenca_cronica',
            field=models.BooleanField(default=False, verbose_name='Doença Crônica'),
        ),
    ]
