# Generated by Django 3.1.5 on 2021-02-13 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CadastroDePessoa', '0004_auto_20210212_1554'),
        ('Historico', '0005_auto_20210213_0008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicofamiliar',
            name='doenca_cronica',
        ),
        migrations.CreateModel(
            name='DoencaCronica',
            fields=[
                ('id_doenca_cronica', models.AutoField(primary_key=True, serialize=False)),
                ('doenca_cronica', models.BooleanField(default=False, verbose_name='Doença Crônica')),
                ('fk_usuario_doenca_cronica', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='CadastroDePessoa.usuario')),
            ],
        ),
    ]
