# Generated by Django 3.1.5 on 2021-02-16 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Historico', '0006_auto_20210213_1818'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicoconsultas',
            options={'ordering': ('-data',)},
        ),
        migrations.AlterField(
            model_name='historicofamiliar',
            name='doenca_hereditarias',
            field=models.TextField(verbose_name='Doenças Hereditarias'),
        ),
    ]
