# Generated by Django 3.1.5 on 2021-02-03 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CadastroDePessoa', '0010_remove_usuario_vacinas'),
        ('Vacinas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacinas',
            name='fk_usuario_vacinas',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='CadastroDePessoa.usuario'),
        ),
    ]
