# Generated by Django 3.1.5 on 2021-02-04 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CadastroDePessoa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoencasExistentes',
            fields=[
                ('id_doencas_existentes', models.AutoField(primary_key=True, serialize=False)),
                ('doenca', models.CharField(max_length=200, verbose_name='Doença')),
                ('ano_diagnostico', models.DateField(verbose_name='Ano do diagnóstico')),
                ('exame', models.FileField(blank=True, upload_to='exames')),
                ('fk_usuario_doencas_existentes', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='CadastroDePessoa.usuario')),
            ],
        ),
    ]
