# Generated by Django 3.1.5 on 2021-02-16 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DoencasExistentes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doencasexistentes',
            options={'ordering': ('-ano_diagnostico',)},
        ),
        migrations.AlterField(
            model_name='doencasexistentes',
            name='ano_diagnostico',
            field=models.DateField(verbose_name='Data do diagnóstico'),
        ),
    ]
