# Generated by Django 3.1.5 on 2021-02-03 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DoencasExistentes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doencasexistentes',
            name='exame',
            field=models.FileField(blank=True, upload_to='exames'),
        ),
    ]
