# Generated by Django 3.1.5 on 2021-02-04 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CadastroDePessoa', '0010_auto_20210203_2052'),
        ('DoencasExistentes', '0002_auto_20210203_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='doencasexistentes',
            name='fk_usuario',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='CadastroDePessoa.usuario'),
        ),
    ]
