# Generated by Django 3.1.5 on 2021-02-16 23:58

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CadastroDePessoa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvaliacaoDiaria',
            fields=[
                ('id_avaliacao_diaria', models.AutoField(primary_key=True, serialize=False)),
                ('sintomas', multiselectfield.db.fields.MultiSelectField(choices=[('dorDeCabeca', 'Dor de Cabeça'), ('dorNoCorpo', 'Dor no corpo'), ('cansaco', 'Cansaço'), ('dorNoEstomago', 'Dor no estômago'), ('inchaco', 'Inchaço'), ('nausea', 'Náusea'), ('coriza', 'Coriza'), ('faltaDeAr', 'Falta de ar'), ('insonia', 'Insonia')], max_length=100, verbose_name='Sintomas')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('outro', models.TextField(blank=True, verbose_name='Outro sintoma')),
                ('data', models.DateField(default=datetime.datetime(2021, 2, 16, 23, 58, 33, 142746, tzinfo=utc), verbose_name='Data ')),
                ('fk_usuario_avaliacao_diaria', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='CadastroDePessoa.usuario')),
            ],
        ),
    ]
