# Generated by Django 3.1.5 on 2021-02-04 01:44

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CadastroDePessoa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvaliacaoDiaria',
            fields=[
                ('id_avaliacao_diaria', models.AutoField(primary_key=True, serialize=False)),
                ('sintomas', multiselectfield.db.fields.MultiSelectField(choices=[('dorDeCabeca', 'Dor de Cabeça'), ('dorNoCorpo', 'Dor no corpo'), ('cansaco', 'Cansaço'), ('dorNoEstomago', 'Dor no estômago'), ('inchaco', 'Inchaço'), ('nausea', 'Náusea'), ('coriza', 'Coriza'), ('faltaDeAr', 'Falta de ar'), ('insonia', 'Insonia'), ('outro', 'Outro')], max_length=50, verbose_name='Sintomas')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('fk_usuario_avaliacao_diaria', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='CadastroDePessoa.usuario')),
            ],
        ),
    ]
