# Generated by Django 3.1.5 on 2021-02-17 00:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('AvaliacaoDiaria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacaodiaria',
            name='data',
            field=models.DateField(default=datetime.datetime(2021, 2, 17, 0, 18, 46, 965492, tzinfo=utc), verbose_name='Data '),
        ),
        migrations.AddField(
            model_name='avaliacaodiaria',
            name='outro',
            field=models.TextField(blank=True, verbose_name='Outro sintoma'),
        ),
        migrations.AlterField(
            model_name='avaliacaodiaria',
            name='sintomas',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('dorDeCabeca', 'Dor de Cabeça'), ('dorNoCorpo', 'Dor no corpo'), ('cansaco', 'Cansaço'), ('dorNoEstomago', 'Dor no estômago'), ('inchaco', 'Inchaço'), ('nausea', 'Náusea'), ('coriza', 'Coriza'), ('faltaDeAr', 'Falta de ar'), ('insonia', 'Insonia')], max_length=100, verbose_name='Sintomas'),
        ),
    ]
