# Generated by Django 3.1.5 on 2021-02-05 18:05

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('AvaliacaoDiaria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacaodiaria',
            name='outro',
            field=models.TextField(blank=True, verbose_name='Outro sintoma'),
        ),
        migrations.AlterField(
            model_name='avaliacaodiaria',
            name='sintomas',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('dorDeCabeca', 'Dor de Cabeça'), ('dorNoCorpo', 'Dor no corpo'), ('cansaco', 'Cansaço'), ('dorNoEstomago', 'Dor no estômago'), ('inchaco', 'Inchaço'), ('nausea', 'Náusea'), ('coriza', 'Coriza'), ('faltaDeAr', 'Falta de ar'), ('insonia', 'Insonia')], max_length=50, verbose_name='Sintomas'),
        ),
    ]
