# Generated by Django 3.1.5 on 2021-02-11 23:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AvaliacaoDiaria', '0002_auto_20210205_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacaodiaria',
            name='data',
            field=models.DateField(default=datetime.datetime(2021, 2, 11, 20, 54, 57, 890839), verbose_name='Data '),
        ),
    ]
