# Generated by Django 3.1.5 on 2021-02-17 16:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('AvaliacaoDiaria', '0002_auto_20210217_0401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacaodiaria',
            name='data',
            field=models.DateField(default=datetime.datetime(2021, 2, 17, 16, 56, 13, 501189, tzinfo=utc), verbose_name='Data '),
        ),
    ]
