# Generated by Django 3.1.5 on 2021-02-13 00:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('AvaliacaoDiaria', '0002_auto_20210212_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacaodiaria',
            name='data',
            field=models.DateField(default=datetime.datetime(2021, 2, 13, 0, 8, 22, 607934, tzinfo=utc), verbose_name='Data '),
        ),
    ]
