# Generated by Django 3.1.5 on 2021-02-13 02:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('AvaliacaoDiaria', '0003_auto_20210212_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacaodiaria',
            name='data',
            field=models.DateField(default=datetime.datetime(2021, 2, 13, 2, 20, 22, 691086, tzinfo=utc), verbose_name='Data '),
        ),
    ]
