# Generated by Django 3.1.5 on 2021-02-03 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AvaliacaoDiaria', '0003_auto_20210203_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacaodiaria',
            name='observacoes',
            field=models.TextField(blank=True, verbose_name='Observações'),
        ),
    ]
