# Generated by Django 3.1.5 on 2021-02-03 18:26

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('AvaliacaoDiaria', '0004_auto_20210203_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacaodiaria',
            name='sintomas',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('dorDeCabeca', 'Dor de Cabeça'), ('dorNoCorpo', 'Dor no corpo'), ('cansaco', 'Cansaço'), ('dorNoEstomago', 'Dor no estômago'), ('inchaco', 'Inchaço'), ('nausea', 'Náusea'), ('coriza', 'Coriza'), ('faltaDeAr', 'Falta de ar'), ('insonia', 'Insonia'), ('outro', 'Outro')], max_length=50, verbose_name='Sintomas'),
        ),
    ]
