# Generated by Django 3.1.5 on 2021-02-12 16:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('AvaliacaoDiaria', '0004_auto_20210211_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacaodiaria',
            name='data',
            field=models.DateField(default=datetime.datetime(2021, 2, 12, 16, 39, 29, 95147, tzinfo=utc), verbose_name='Data '),
        ),
    ]
