# Generated by Django 3.1.5 on 2021-02-04 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CadastroDePessoa', '0011_remove_usuario_avaliacao_diaria'),
        ('AvaliacaoDiaria', '0005_auto_20210203_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacaodiaria',
            name='fk_usuario_avaliacao_diaria',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='CadastroDePessoa.usuario'),
        ),
    ]
