# Generated by Django 3.1.5 on 2021-02-12 18:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('AvaliacaoDiaria', '0005_auto_20210212_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacaodiaria',
            name='data',
            field=models.DateField(default=datetime.datetime(2021, 2, 12, 18, 36, 56, 878650, tzinfo=utc), verbose_name='Data '),
        ),
    ]
