# Generated by Django 3.1.5 on 2021-02-13 03:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('AvaliacaoDiaria', '0005_auto_20210212_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacaodiaria',
            name='data',
            field=models.DateField(default=datetime.datetime(2021, 2, 13, 3, 8, 9, 385241, tzinfo=utc), verbose_name='Data '),
        ),
    ]
