# Generated by Django 3.1.5 on 2021-02-12 18:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('AvaliacaoDiaria', '0006_auto_20210212_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacaodiaria',
            name='data',
            field=models.DateField(default=datetime.datetime(2021, 2, 12, 18, 42, 33, 298726, tzinfo=utc), verbose_name='Data '),
        ),
    ]
