# Generated by Django 3.1.5 on 2021-02-12 18:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('AvaliacaoDiaria', '0007_auto_20210212_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacaodiaria',
            name='data',
            field=models.DateField(default=datetime.datetime(2021, 2, 12, 18, 54, 55, 622654, tzinfo=utc), verbose_name='Data '),
        ),
    ]
