# Generated by Django 3.1.5 on 2021-02-13 23:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('AvaliacaoDiaria', '0010_auto_20210213_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacaodiaria',
            name='data',
            field=models.DateField(default=datetime.datetime(2021, 2, 13, 23, 31, 21, 778763, tzinfo=utc), verbose_name='Data '),
        ),
    ]
