# Generated by Django 3.1.5 on 2021-02-14 01:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('AvaliacaoDiaria', '0011_auto_20210213_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacaodiaria',
            name='data',
            field=models.DateField(default=datetime.datetime(2021, 2, 14, 1, 53, 29, 902931, tzinfo=utc), verbose_name='Data '),
        ),
    ]
