# Generated by Django 3.1.5 on 2021-02-14 02:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('AvaliacaoDiaria', '0012_auto_20210213_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacaodiaria',
            name='data',
            field=models.DateField(default=datetime.datetime(2021, 2, 14, 2, 7, 18, 701485, tzinfo=utc), verbose_name='Data '),
        ),
    ]
