# Generated by Django 3.1.5 on 2021-02-14 19:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('AvaliacaoDiaria', '0013_auto_20210213_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacaodiaria',
            name='data',
            field=models.DateField(default=datetime.datetime(2021, 2, 14, 19, 28, 7, 642814, tzinfo=utc), verbose_name='Data '),
        ),
    ]
