# Generated by Django 3.1.5 on 2021-02-16 00:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('AvaliacaoDiaria', '0014_auto_20210214_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacaodiaria',
            name='data',
            field=models.DateField(default=datetime.datetime(2021, 2, 16, 0, 38, 14, 998133, tzinfo=utc), verbose_name='Data '),
        ),
    ]
