# Generated by Django 3.1.5 on 2021-02-16 17:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('AvaliacaoDiaria', '0015_auto_20210215_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacaodiaria',
            name='data',
            field=models.DateField(default=datetime.datetime(2021, 2, 16, 17, 31, 4, 918992, tzinfo=utc), verbose_name='Data '),
        ),
        migrations.AlterField(
            model_name='avaliacaodiaria',
            name='sintomas',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('dorDeCabeca', 'Dor de Cabeça'), ('dorNoCorpo', 'Dor no corpo'), ('cansaco', 'Cansaço'), ('dorNoEstomago', 'Dor no estômago'), ('inchaco', 'Inchaço'), ('nausea', 'Náusea'), ('coriza', 'Coriza'), ('faltaDeAr', 'Falta de ar'), ('insonia', 'Insonia')], max_length=100, verbose_name='Sintomas'),
        ),
    ]
