# Generated by Django 3.1.5 on 2021-02-16 16:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('AvaliacaoDiaria', '0015_auto_20210215_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacaodiaria',
            name='data',
            field=models.DateField(default=datetime.datetime(2021, 2, 16, 16, 46, 45, 228405, tzinfo=utc), verbose_name='Data '),
        ),
    ]
