# Generated by Django 3.1.5 on 2021-01-27 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamentos',
            fields=[
                ('id_medicamentos', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField(verbose_name='Nome Medicamento')),
                ('funcao', models.TextField(blank=True, verbose_name='Função')),
                ('data_inicio', models.DateField(blank=True, verbose_name='Data de Início')),
                ('data_final', models.DateField(blank=True, verbose_name='Data Final')),
                ('infos_extras', models.TextField(blank=True, verbose_name='Informações Extras')),
            ],
        ),
    ]
