# Generated by Django 3.1.5 on 2021-02-16 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Medicacao', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banco_Medicamento_Anvisa',
        ),
        migrations.AlterModelOptions(
            name='medicamentos',
            options={'ordering': ('-data_inicio',)},
        ),
        migrations.RemoveField(
            model_name='medicamentos',
            name='infos_extras',
        ),
    ]
