# Generated by Django 3.1.5 on 2021-02-01 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medicacao', '0003_auto_20210201_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicamentos',
            name='nome',
            field=models.TextField(default='', verbose_name='Nome Medicamento'),
        ),
    ]
