# Generated by Django 3.1.5 on 2021-02-01 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Medicacao', '0005_auto_20210201_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamentos',
            name='nome',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Medicacao.banco_medicamento_anvisa'),
        ),
    ]
