# Generated by Django 3.1.5 on 2021-02-01 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Medicacao', '0006_auto_20210201_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicamentos',
            name='nome',
        ),
        migrations.AddField(
            model_name='medicamentos',
            name='fk_nome',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Medicacao.banco_medicamento_anvisa', verbose_name='nome'),
        ),
    ]
