# Generated by Django 3.1.5 on 2021-02-04 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CadastroDePessoa', '0010_auto_20210203_2052'),
        ('Medicacao', '0007_auto_20210201_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicamentos',
            name='fk_nome',
        ),
        migrations.AddField(
            model_name='medicamentos',
            name='fk_user_medicacao',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='CadastroDePessoa.usuario'),
        ),
        migrations.AddField(
            model_name='medicamentos',
            name='nome',
            field=models.CharField(default='', max_length=100, verbose_name='Nome'),
        ),
    ]
