# Generated by Django 3.1.5 on 2021-02-16 23:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import stdimage.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('foto', stdimage.models.StdImageField(blank=True, upload_to='perfil_user')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('sexo', models.CharField(choices=[('masculino', 'Masculino'), ('feminino', 'Feminino'), ('outro', 'Outro'), ('sem_resposta', 'Prefiro não responder')], max_length=21, verbose_name='Sexo')),
                ('telefone', models.CharField(default='00', max_length=13, verbose_name='Telefone')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('qrcode', models.TextField(blank=True, verbose_name='QRCode')),
                ('hash_user', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Hash User')),
                ('id_fk_cadastro_user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='CadastroUser')),
            ],
        ),
    ]
