# Generated by Django 3.1.5 on 2021-01-27 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Cirurgias', '0001_initial'),
        ('DoencasExistentes', '0001_initial'),
        ('AvaliacaoDiaria', '0001_initial'),
        ('Medicacao', '0001_initial'),
        ('AlergiaIntolerancia', '0001_initial'),
        ('Vacinas', '0001_initial'),
        ('Sangue', '0001_initial'),
        ('Historico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('foto', models.ImageField(blank=True, upload_to='midia/usuario_img')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('sexo', models.CharField(choices=[('masculino', 'Masculino'), ('feminino', 'Feminino'), ('outro', 'Outro'), ('sem_resposta', 'Prefiro não responder')], max_length=21, verbose_name='Sexo')),
                ('telefone', models.CharField(default='00', max_length=13, unique=True, verbose_name='Telefone')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('senha', models.CharField(max_length=40, verbose_name='Senha')),
                ('alergias', models.ManyToManyField(to='AlergiaIntolerancia.Alergias')),
                ('avaliacao_diaria', models.ManyToManyField(to='AvaliacaoDiaria.AvaliacaoDiaria')),
                ('cirurgias', models.ManyToManyField(to='Cirurgias.Cirurgias')),
                ('doencas', models.ManyToManyField(to='DoencasExistentes.DoencasExistentes')),
                ('historico_consultas', models.ManyToManyField(to='Historico.HistoricoConsultas')),
                ('historico_familiar', models.ManyToManyField(to='Historico.HistoricoFamiliar')),
                ('intolerancias', models.ManyToManyField(to='AlergiaIntolerancia.Intolerancias')),
                ('medicacao', models.ManyToManyField(to='Medicacao.Medicamentos')),
                ('sangue', models.ManyToManyField(to='Sangue.TipoSanguineo')),
                ('vacinas', models.ManyToManyField(to='Vacinas.Vacinas')),
            ],
        ),
    ]
