# Generated by Django 3.1.5 on 2021-02-17 00:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('CadastroDePessoa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='hash_user',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Hash User'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='qrcode',
            field=models.TextField(blank=True, verbose_name='QRCode'),
        ),
    ]
