# Generated by Django 3.1.5 on 2021-01-22 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CadastroDePessoa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='telefone',
            field=models.CharField(default='00', max_length=13, unique=True, verbose_name='Telefone'),
        ),
    ]
