# Generated by Django 3.1.5 on 2021-01-28 23:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CadastroDePessoa', '0002_usuario_id_fk_cadastro_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='id_fk_cadastro_user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='CadastroUser'),
        ),
    ]
