# Generated by Django 3.1.5 on 2021-02-12 18:42

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('CadastroDePessoa', '0002_usuario_qrcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='qrcode',
            field=stdimage.models.StdImageField(blank=True, upload_to='qrcode', verbose_name='QRCode'),
        ),
    ]
