# Generated by Django 3.1.5 on 2021-02-13 22:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('CadastroDePessoa', '0004_auto_20210212_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='hash_user',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Hash User'),
        ),
    ]
