# Generated by Django 3.1.5 on 2021-01-29 18:18

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('CadastroDePessoa', '0004_remove_usuario_senha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=stdimage.models.StdImageField(blank=True, upload_to='midia/usuario_img'),
        ),
    ]
