# Generated by Django 3.1.5 on 2021-01-29 19:06

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('CadastroDePessoa', '0006_auto_20210129_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=stdimage.models.StdImageField(blank=True, upload_to='perfil_user'),
        ),
    ]
