# Generated by Django 3.1.5 on 2021-02-03 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CadastroDePessoa', '0008_auto_20210129_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='sangue',
        ),
    ]
