# Generated by Django 3.1.5 on 2021-02-03 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CadastroDePessoa', '0009_remove_usuario_sangue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='alergias',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='avaliacao_diaria',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='cirurgias',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='doencas',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='historico_consultas',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='historico_familiar',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='intolerancias',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='medicacao',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='vacinas',
        ),
    ]
