# Generated by Django 3.1.5 on 2021-02-04 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CadastroDePessoa', '0010_remove_usuario_vacinas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='cirurgias',
        ),
    ]
